name: Auto Excel Report
permissions:
  contents: write

on:
  push:
    paths:
      - 'data/*.xlsx'
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install libraries
        run: pip install pandas openpyxl

      - name: Run report script
        run: python script.py

      - name: Commit and push report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "update report" || echo "No changes"
          git push
